config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
      end
    end
  end

  root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    completed_at.present?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy

  def count_total_items
    todo_items.where(todo_list_id: self.id).count
  end

  def count_completed_items
    todo_items.where.not(completed_at: nil).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Client was removed."
    else
      flash[:error] = "Error - could not remove client."
    end
    redirect_to @todo_list
  end

  def update
    @todo_item = @todo_list.todo_items.update(todo_item_params)
  end

  def show
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params.require(:id).permit(:content, :date_added)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: "#{@todo_list.title} - Affiliate created." }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: "#{@todo_list.title} - Affiliate updated." }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: "#{@todo_list.title} - Affiliate deleted." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_list_params
    params.require(:todo_list).permit(:title, :website, :email, :location, :percentage, :paypal_email, :status, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

<body>

<div class="container">
    <%= yield %>
   </div>
    
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "new-client.myshopify.com" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_form_add.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "new-client.myshopify.com" %>
    <div class="actions">
      <div id="submit">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/todo_items/_form_edit.html.erb
<%#= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
<%= form_with(model: todo_items, local: true) do |f| %>


  <div class="affiliate_form">
    <div class="details_edit">
      <div class="field">
        <%= f.label :content %>
        <%= f.text_field :content, value: @todo_item.content %>
      </div>
      <div class="field">
        <%= f.label :date_added %>
        <%= f.date_field :date_added, value: @todo_item.date_added %>
      </div>
    </div>

    <div class="actions">
      <div id="submit">
        <%= f.submit %>
      </div>
      <div id="cancel">
        <%= f.submit 'Cancel', :name => 'cancel' %>
      </div>
    </div>
  </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
    <div class="Client_domain">
      <p><%= todo_item.content %></p>
    </div>
    <div class="client_date attached">
      <p>Date attached<%= todo_item.date_added %></p>
    </div>
    <div class="todo_item">
      <p>Date first paid<%= todo_item.first_paid_at %></p>
    </div>
    <div class="todo_item">
      <p>Date last paid<%= todo_item.last_paid_at %></p>
    </div>
    <div class="trash">
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
</div>

app/views/todo_items/show.html.erb
<h1 class="affliate_title"><%= @todo_list.title %></h1>
<h2 class="affliate_sub_title">Edit - <%= @todo_item.content %></h2>
<div class="forms">
  <%= render 'form_edit', todo_items: @todo_items %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="affiliate_form">
    <div class="details_edit">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>
      <div class="field">
        <%= form.label :website %>
        <%= form.text_field :website %>
      </div>
      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      <div class="field">
        <%= form.label :location %>
        <%= form.text_field :location %>
      </div>
      <div class="field">
        <%= form.label :percentage %>
        <%= form.text_field :percentage %>
      </div>
      <div class="field">
        <%= form.label :paypal_email %>
        <%= form.text_field :paypal_email %>
      </div>
      <div class="field">
        <%= form.label :status %>
        <%= form.select( "status", ["Active", "Out", "Pending", "Writer", "Archived"]) %>
      </div>
    </div>

    <div class="details_desc">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="actions">
      <div id="submit">
        <%= form.submit %>
      </div>
      <div id="cancel">
        <%= link_to 'Cancel', todo_lists_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="affliate_title">Edit - <%= @todo_list.title %></h1>
<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page_title"><h1>Affiliates</h1></div>

<div class="add_list"><%= link_to 'Add Affiliate', new_todo_list_path %></div>

<table id=affiliates_table>
  <thead>
    <tr>
      <th>Affiliate</th>
      <th>Name</th>
      <th>Email</th>
      <th>Stores</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.order(:id).each do |todo_list| %>
      <tr>
        <td id=af_title><%= todo_list.title %></td>
        <td id=af_name><%= todo_list.title %></td>
        <td id=af_email><%= todo_list.email %></td>
        <td id=af_stores><%= todo_list.todo_items.length %></td>
        <td id=af_status><%= todo_list.status %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todo_lists/new.html.erb
<h1 class="affliate_title">New Todo List</h1>
<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="affliate_title"><%= @todo_list.title %></h2>
<p class="affliate_sub_title">Name - <%= @todo_list.title %> - Status</p>

<table id=af_clients_table>
  <thead>
    <tr>
      <th>Store Domain</th>
      <th>Date Added</th>
      <th>Date First Paid</th>
      <th>Date Last Paid</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.todo_items.order(:id).each do |todo_items| %>
      <tr>
        <td id=af_cl_domain><%= todo_items.content %></td>
        <td id=af_cl_created_at><%= todo_items.date_added %></td>
        <td id=af_cl_first_paid><%= todo_items.first_paid_at %></td>
        <td id=af_cl_last_paid><%= todo_items.last_paid_at %></td>
        <td class="edit"><%= link_to todo_list_todo_item_path(@todo_list, todo_items.id) do %>
          <i class="fa fa-edit"></i>
        <% end %></td>
        <td class="trash"><%= link_to todo_list_todo_item_path(@todo_list, todo_items.id), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fa fa-trash"></i>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table id=affiliate_details_table>
    <tr>
      <th>Website</th>
      <td id=af_detail><%= @todo_list.website %></td>
    </tr>
    <tr>
      <th>Email</th>
        <td id=af_detail><%= @todo_list.email %></td>
    </tr>
    <tr>
      <th>Location</th>
        <td id=af_detail><%= @todo_list.location %></td>
    </tr>
    <tr>
      <th>Percent</th>
        <td id=af_detail><%= @todo_list.percentage %></td>
    </tr>
    <tr>
      <th>PayPal Email</th>
        <td id=af_detail><%= @todo_list.paypal_email %></td>
    </tr>
    <tr>
      <th>Since date</th>
        <td id=af_detail><%= @todo_list.created_at %></td>
    </tr>
    <tr>
      <th>Status</th>
        <td id=af_detail><%= @todo_list.status %></td>
    </tr>
    <tr>
      <th>Notes</th>
        <td id=af_detail><%= @todo_list.description %></td>
    </tr>
</table>

<div id="add_client_form">
  <%= render "todo_items/form_add" %>
</div>


<!--<div id="af_clients_wrapper">
  <%= render @todo_list.todo_items.order(:id) %>
  <div id="form">
    <%= render "todo_items/form_add" %>
  </div>
</div>-->

<div class="links">
  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
  <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %> |
  <%= link_to 'Back', todo_lists_path %>
</div>